os: linux
dist: bionic

language: python
python:
  - "3.6"
  - "3.7"

before_install:
  # clean up travis golang installation
  - which go
  - rm -rf $(which go)
  - rm -rf /home/travis/gopath/*

install:
 - pip install requests
 - python3 ./thirdparty.py
 
script:
 - pytest
