name: Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: [3.6]
        go: [1.13]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    
    # I couldn't figure out a way to uninstall the default golang, and install go by thirdpart.py
    # So we get to install the correct go version
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: run thirdpart.py
      run: python3 ./thirdparty.py
      
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: pytest
      run: |
        pip install pytest requests
        CI=gihub pytest