name: Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    
    # The GitHub CI may already installed 1.12 version
    # If we run ./thirdparty.py and without this setup, there exist 1.12 and 1.13 simultaneously
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Install pypi libraries
      run: pip install pytest flake8 requests

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Install dependencies
      run: |
        python3 ./thirdparty.py

    - name: Test with pytest
      run: |
        pytest
